# See: https://gohugo.io/getting-started/configuration/
baseURL: https://ar.to/
title: Arto Bendiken
languageCode: en-us
languageName: English
#googleAnalytics: UA-83574-11
uglyURLs: true
metaDataFormat: yaml

# See: https://gohugo.io/getting-started/configuration/
theme: academic
paginate: 100
summaryLength: 70
enableEmoji: true
copyright:

# See: https://gohugo.io/content-management/urls/#permalinks
permalinks:
  categories: /categories/:slug
  tags: /tags/:slug
  essays: /:year/:month/:filename
  talks: /:year/:month/:filename

# See: https://gohugo.io/content-management/taxonomies#configure-taxonomies
taxonomies:
  category: categories
  tag: tags
  author: authors

# See: https://gohugo.io/getting-started/configuration/#configure-front-matter
frontmatter:
  date:
    - created
    - date
    - publishDate
    - lastmod
  lastmod:
    - modified
    - lastmod
    - date
    - publishDate
  publishDate:
    - published
    - publishDate
    - date
  expiryDate:
    - expires
    - expiryDate

# See: https://gohugo.io/getting-started/configuration-markup
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

# See: https://gohugo.io/templates/output-formats/
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS

mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest

outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
