main:
  - name: Talks
    url: '#talks'
    weight: 20
  - name: Essays
    url: '#essays'
    weight: 30
  - name: Reviews
    url: '#reviews'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 90
